#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /login
  controller : App\Controller\SeConnecterController::login

signoff:
  path: /signoff
  controller : App\Controller\SeConnecterController::signoff

visiteur:
  path: /visiteur-medical/espace
  controller : App\Controller\VisiteurController::espace

setfraisforfait:
  path: /test
  controller : App\Controller\VisiteurController::setfraisforfait

addfichefrais:
  path: /test2
  controller : App\Controller\VisiteurController::addfichefrais

removefichefrais:
  path: /test3
  controller: App\Controller\VisiteurController::removefichefrais

setfraishorsforfait:
  path: /test4
  controller: App\Controller\VisiteurController::setfraishorsforfait

comptable:
  path: /comptable/espace
  controller : App\Controller\ComptableController::espace